//! This file is automatically generated.
//!
//! Date: 2022-12-19T20:20:06
use crate::bitman::checked::index::IndexU32;
use crate::bitman::checked::index::IndexU8;
use crate::bitman::checked::index::I;
impl IndexU8 for I<0> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        0
    }
}
impl IndexU8 for I<1> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        1
    }
}
impl IndexU8 for I<2> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        2
    }
}
impl IndexU8 for I<3> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        3
    }
}
impl IndexU8 for I<4> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        4
    }
}
impl IndexU8 for I<5> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        5
    }
}
impl IndexU8 for I<6> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        6
    }
}
impl IndexU8 for I<7> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        7
    }
}
impl IndexU32 for I<0> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        0
    }
}
impl IndexU32 for I<1> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        1
    }
}
impl IndexU32 for I<2> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        2
    }
}
impl IndexU32 for I<3> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        3
    }
}
impl IndexU32 for I<4> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        4
    }
}
impl IndexU32 for I<5> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        5
    }
}
impl IndexU32 for I<6> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        6
    }
}
impl IndexU32 for I<7> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        7
    }
}
impl IndexU32 for I<8> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        8
    }
}
impl IndexU32 for I<9> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        9
    }
}
impl IndexU32 for I<10> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        10
    }
}
impl IndexU32 for I<11> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        11
    }
}
impl IndexU32 for I<12> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        12
    }
}
impl IndexU32 for I<13> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        13
    }
}
impl IndexU32 for I<14> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        14
    }
}
impl IndexU32 for I<15> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        15
    }
}
impl IndexU32 for I<16> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        16
    }
}
impl IndexU32 for I<17> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        17
    }
}
impl IndexU32 for I<18> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        18
    }
}
impl IndexU32 for I<19> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        19
    }
}
impl IndexU32 for I<20> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        20
    }
}
impl IndexU32 for I<21> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        21
    }
}
impl IndexU32 for I<22> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        22
    }
}
impl IndexU32 for I<23> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        23
    }
}
impl IndexU32 for I<24> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        24
    }
}
impl IndexU32 for I<25> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        25
    }
}
impl IndexU32 for I<26> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        26
    }
}
impl IndexU32 for I<27> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        27
    }
}
impl IndexU32 for I<28> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        28
    }
}
impl IndexU32 for I<29> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        29
    }
}
impl IndexU32 for I<30> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        30
    }
}
impl IndexU32 for I<31> {
    #[inline]
    #[must_use]
    fn value(self) -> usize {
        31
    }
}
