name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build with standard library
      run: cargo build --verbose
    - name: Run tests with standard library
      run: cargo test --verbose
    - name: Build without standard library
      run: cargo build --verbose --features no-std
    - name: Run tests without standard library
      run: cargo test --verbose --features no-std
